### ISSUE TITLE
Admin panel'de star-ratings yıldızları yerine html tagı görünmesi sorunu.

### ISSUE THREAD

**Issue by summersonnn** [summersonnn/Photash-Django-Based-web-platform#3]
İşaretli kısımda yıldızlar gözükmesi lazım.

![nostar](https://user-images.githubusercontent.com/31991669/35780931-0dfcfb44-09f4-11e8-8d26-fe7ede34a18f.jpg)

**Comment by cgencer** [comment]
django'da string'i basarken ekrana output etmede sorun var; muhtemelen django'nun bir şekilde render ettirmesini force eden bir ayarla yapılabilir. hmtl veya js ile alakalı değil bu.
